[variables]
NIXPACKS_NODE_VERSION = "22"
NIXPACKS_PHP_VERSION = "8.4"
NODE_ENV = "production"
NPM_CONFIG_INCLUDE = "dev"
COMPOSER_ALLOW_SUPERUSER = "1"
PHP_UPLOAD_MAX_FILESIZE = "1024M"
PHP_POST_MAX_SIZE = "2048M"
PHP_MAX_FILE_UPLOADS = "200"
NGINX_CLIENT_MAX_BODY_SIZE = "0"
